export const FETCH_SEARCH_MOVIES_REQUEST = "FETCH_SEARCH_MOVIES_REQUEST";
export const FETCH_SEARCH_MOVIES_SUCCESS = "FETCH_SEARCH_MOVIES_SUCCESS";
export const FETCH_SEARCH_MOVIES_FAILURE = "FETCH_SEARCH_MOVIES_FAILURE";
export const CLEAR_SEARCH_MOVIES = 'CLEAR_SEARCH_MOVIES';